"""Write the data tables and count macros that Figure 6 reads."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np
import pandas as pd

from brainturtle import config as cfg
from brainturtle import data, featuresets as fs

RES = cfg.RESULTS / f"n{cfg.N_PERM}"
OUT = Path(__file__).resolve().parent / "assets"

STREAMS = [("MFCC", 13), ("Spectral", 3), ("Pitch", 1), ("Energy", 1)]
N_STATS = 6


def numbers():
    feats = fs.common_features()
    n = len(feats)
    fam = pd.Series([fs.categorize(f) for f in feats]).value_counts()
    drop = fs.drop_set()
    coh = pd.read_csv(RES / "table1_cohorts.csv").set_index("cohort")
    cv = data.commonvoice()
    cv_meta = pd.read_csv(cfg.DATA / "commonvoice_metadata_clean.csv")

    for name, k in STREAMS:
        assert fam[name] == k * N_STATS, (name, fam[name])
    assert fam["Voice Quality"] + sum(k * N_STATS for _, k in STREAMS) == n

    m = {
        "Nfeat": n,
        "nMFCC": fam["MFCC"], "nSpec": fam["Spectral"], "nPitch": fam["Pitch"],
        "nEnergy": fam["Energy"], "nVoice": fam["Voice Quality"],
        "nStats": N_STATS,
        "nDrop": len(drop), "nKeep": n - len(drop),
        "dropPct": int(round(cfg.PRIMARY_THRESHOLD * 100)),
        "CVspk": len(cv), "CVrec": len(cv_meta),
        "CVbands": cv["age_num_x"].nunique(),
        "CVageMin": int(cv["age_num_x"].min()),
        "CVageMax": int(cv["age_num_x"].max()),
        "PittSpk": int(coh.loc["DementiaBank Pitt", "n_speakers"]),
        "PittAD": int(coh.loc["DementiaBank Pitt", "n_ad"]),
        "PittCtrl": int(coh.loc["DementiaBank Pitt", "n_control"]),
        "KangSpk": int(coh.loc["Kang", "n_speakers"]),
        "KangAD": int(coh.loc["Kang", "n_ad"]),
        "KangCtrl": int(coh.loc["Kang", "n_control"]),
        "ADRSpk": int(coh.loc["ADReSSo-2021", "n_speakers"]),
        "ADRAD": int(coh.loc["ADReSSo-2021", "n_ad"]),
        "ADRCtrl": int(coh.loc["ADReSSo-2021", "n_control"]),
        "nSeeds": len(cfg.SEEDS),
        "testPct": int(round(cfg.TEST_SIZE * 100)),
        "nBoot": f"{cfg.N_BOOT:,}",
    }

    lad = pd.read_csv(RES / "fig2a_removal_ladder.csv").set_index("drop_pct")
    base = lad.loc[0.0]
    cut = lad.loc[cfg.PRIMARY_THRESHOLD]
    ext = pd.read_csv(RES / "fig4_external.csv").set_index("cohort")
    m.update({
        "AUCbase": f"{base['auc_point']:.3f}",
        "AUCcut": f"{cut['auc_point']:.3f}",
        "AUCdelta": f"{cut['delta_vs_baseline']:+.3f}",
        "Pcut": f"{cut['p_wald']:.4f}".rstrip("0"),
        "AUCkang": f"{ext.loc['Kang', 'auc']:.2f}",
        "AUCadr": f"{ext.loc['ADReSSo-2021', 'auc']:.2f}",
    })

    cat = pd.read_csv(RES / "fig3_category_rates.csv").set_index("category")
    kept = (cat["total"] - cat["dropped"]).astype(int)
    m.update({
        "kMFCC": kept["MFCC"], "kSpec": kept["Spectral"],
        "kPitch": kept["Pitch"], "kEnergy": kept["Energy"],
        "kVoice": kept["Voice Quality"],
    })
    assert sum(kept) == n - len(drop)

    top = fs.load_shap_ranking()["feature"].tolist()[:4]
    m["TopRemoved"] = ", ".join(f.replace("_", r"\_") for f in top)
    lines = ["% generated by figure6_assets.py -- do not edit"]
    for k, v in m.items():
        lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    (OUT / "fig6_numbers.tex").write_text("\n".join(lines) + "\n")
    return m


def ages():
    """Speakers per decade band for the three age-bearing corpora."""
    edges = np.arange(10, 100, 10)
    labels = [f"{lo}s" for lo in edges[:-1]]

    def decade(series):
        c = pd.cut(series, bins=edges, right=False, labels=labels)
        return c.value_counts().reindex(labels, fill_value=0)

    cv = data.commonvoice()["age_num_x"]
    pitt = data.pitt_with_age().drop_duplicates("speaker_int")["entryage"]
    kang = pd.read_csv(RES / "kang_speaker_table.csv")["age"]
    df = pd.DataFrame({"band": labels,
                       "commonvoice": decade(cv).values,
                       "pitt": decade(pitt).values,
                       "kang": decade(kang).values})
    df["x"] = edges[:-1]
    df.to_csv(OUT / "fig6_ages.dat", sep=" ", index=False)
    return df


def ranking():
    feats = set(fs.common_features())
    rk = fs.load_shap_ranking()
    rk = rk[rk["feature"].isin(feats)].reset_index(drop=True)
    drop = set(fs.drop_set())
    val = [c for c in rk.columns if c != "feature"][0]
    df = pd.DataFrame({"rank": rk.index + 1,
                       "feature": rk["feature"],
                       "shap": rk[val].round(4),
                       "removed": rk["feature"].isin(drop).astype(int),
                       "family": [fs.categorize(f).replace(" ", "")
                                  for f in rk["feature"]]})
    assert df["removed"].sum() == len(drop)
    df.to_csv(OUT / "fig6_ranking.dat", sep=" ", index=False)
    return df


N_BEESWARM = 12


def beeswarm():
    """Age-model SHAP profile for the top features, jittered for pgfplots."""
    bee = pd.read_csv(RES / "age_model_shap_values.csv")
    order = (bee.groupby("feature")["rank"].first().sort_values()
                .index.tolist()[:N_BEESWARM])
    rng = np.random.default_rng(0)
    rows = []
    for i, feat in enumerate(order):
        d = bee[bee.feature == feat]
        y = (N_BEESWARM - 1 - i) + rng.uniform(-0.3, 0.3, len(d))
        rows.append(pd.DataFrame({"y": y.round(3), "shap": d["shap"].round(3),
                                  "val": d["feature_value_norm"].round(3)}))
    df = pd.concat(rows, ignore_index=True)
    df.to_csv(OUT / "fig6_beeswarm.dat", sep=" ", index=False)
    labels = ",".join(f.replace("_", r"\_") for f in order[::-1])
    (OUT / "fig6_beeswarm_labels.tex").write_text(
        "% generated by figure6_assets.py -- do not edit\n"
        f"\\newcommand{{\\BeeLabels}}{{{labels}}}\n"
        f"\\newcommand{{\\nBee}}{{{N_BEESWARM}}}\n")
    return df


def category():
    """Preferential pruning by acoustic domain, as in Figure 3a."""
    cat = pd.read_csv(RES / "fig3_category_rates.csv")
    overall = cat["dropped"].sum() / cat["total"].sum()
    cat = cat.sort_values("rate", ascending=False).reset_index(drop=True)
    above = cat["rate"] > overall
    df = pd.DataFrame({"x": range(len(cat)),
                       "category": cat["category"].str.replace(" ", "~"),
                       "rate": cat["rate"].round(4),
                       "dropped": cat["dropped"].astype(int),
                       "total": cat["total"].astype(int),
                       "above": above.astype(int)})
    df["rate_above"] = np.where(above, df["rate"], np.nan)
    df["rate_below"] = np.where(above, np.nan, df["rate"])
    df.to_csv(OUT / "fig6_category.dat", sep=" ", index=False, na_rep="nan")
    annot = ",".join(f"{i}/{{{d}/{t}}}/{r}" for i, d, t, r in
                     zip(df["x"], df["dropped"], df["total"], df["rate"]))
    with (OUT / "fig6_numbers.tex").open("a") as fh:
        fh.write(f"\\newcommand{{\\OverallRate}}{{{overall:.3f}}}\n")
        fh.write(f"\\newcommand{{\\OverallFrac}}{{{int(cat['dropped'].sum())}/"
                 f"{int(cat['total'].sum())}}}\n")
        fh.write("\\newcommand{\\CatLabels}{" + ",".join(df["category"]) + "}\n")
        fh.write("\\newcommand{\\CatAnnot}{" + annot + "}\n")
    return df


def main():
    OUT.mkdir(exist_ok=True)
    m = numbers()
    a = ages()
    r = ranking()
    b = beeswarm()
    c = category()
    print("    -> assets/fig6_beeswarm.dat %d points, %d features"
          % (len(b), N_BEESWARM))
    print("    -> assets/fig6_category.dat %s" % c["category"].tolist())
    print("    -> assets/fig6_numbers.tex  %d macros" % len(m))
    print("    -> assets/fig6_ages.dat     %s" % a[["commonvoice", "pitt", "kang"]].sum().to_dict())
    print("    -> assets/fig6_ranking.dat  %d features, %d removed"
          % (len(r), r["removed"].sum()))


if __name__ == "__main__":
    main()
